services:
  app:
    build:
      context: .
      target: development
    ports:
      - "${APP_PORT}:${HOST_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SSL_MODE=${SSL_MODE}
      - RUNTIME_INTERVAL=${RUNTIME_INTERVAL}
      - RATIO=${RATIO}
      - MODE=${MODE}
      - GRACE=${GRACE}
      - ORDERING=${ORDERING}
      - HEALTH_CHECK_PORT=${HEALTH_CHECK_PORT}
      - ENVIRONMENT=docker
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data:
